# Site
name: "teachmehow.tech"
title: "techmehow.tech"
description: "teachmehow.tech is a technology blog focused on detailing the things I'm working on and learning. It used to be called teachmehowtoroute but since I've expanded my horizons, teachmehow.tech seems far more fitting"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'A-118602217-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  james:
    name: James P. Krause
    display_name: James
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: james@teachmehow.tech
    web: https://teachmehow.tech
    description: "It's me, James. I'm just another nerd who loves technology and hockey."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
