# Site
name: "프로젝트 ZZOM (사이트 준비중)"
title: "프로젝트 ZZOM (사이트 준비중)"
description: "One-person Publishing Project"
logo: 'assets/images/zzom-logo-dark (48 x 48).png'
favicon: 'favicon.ico'
baseurl: 
google_analytics: 'UA-192688751-1'
disqus: 'zzom'
mailchimp-list: 'https://gmail.us2.list-manage.com/subscribe/post?u=f0c2c860abc78e38661cc5458&amp;id=fa3043bfc8'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  # sal:
  #   name: Sal
  #   display_name: Sal
  #   gravatar: e56154546cf4be74e393c62d1ae9f9d4
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  admin:
    name: admin
    display_name: ZZOM
    avatar: 'assets/images/zzom-logo-dark (200 x 200).png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: project.zzom@gmail.com
    web: https://zzom.io
    twitter: https://twitter.com/project_zzom
    description: "노잼 공식 대변인 / 공식 정보를 제공하고 존댓말을 씁니다."
  bomber:
    name: Shin Sang-jae
    display_name: 번역하는 개발자   
    avatar: 'assets/images/avatar-bomber.jpg'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: codelabor@gmail.com
    web: https://about.me/codelabor
    twitter: https://twitter.com/codelabor
    description: "드립치는 어그로꾼 / 잡담과 스포를 담당하고 혼잣말을 합니다."  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-5050141342916334"
adsense-data-ad-slot: "1542083085"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
