# Site
name: "Blog sobre Desarrollo de Software"
title: "Blog de Desarrollo de Software"
description: "Blog especializado en el desarrollo de software en .NET. Contenidos complementarios: diseño y arquitectura de software, DevOps, virtualización, etc."
logo: 'assets/images/dotnetguy-header-logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-EJLMH0PQZT'
disqus: 'https-didacrius-github-io'
mailchimp-list: 'https://github.us9.list-manage.com/subscribe?u=b67af2485d1062a2d2e43e4f3&id=d896c7a285'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  didac:
      name: Didac Rius
      display_name: Didac Rius    
      avatar: 'assets/images/didacrius-author-avatar.png'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: didacriuscom@gmail.com
      web: https://www.didacrius.github.io
      twitter: https://twitter.com/DidacRius
      description: "Ingeniero de software especializado en la tecnología .NET. Sólidos conocimientos en .NET Framework, .NET Core y Angular frameworks, así como en diseño y arquitectura de software, DevOps y virtualización."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
