# Site
name: "loda-kun"
title: "loda-kun"
description: "Blog của loda"
meta_description: "Blog hướng dẫn java và tất cả hệ sinh thái quanh java"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: loda
    display_name: loda
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: loda.namnh@gmail.com
    web: https://www.loda-kun.github.io
    facebook: https://www.facebook.com/nam.tehee
    description: "Là chàng coder nội tâm :'("
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page/:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
