# Site
name: "Silhouettes"
title: "silhouettes"
description: ""Fashions fade, style is eternal." —Yves Saint Laurent"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Trinny
    display_name: Trinny London
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tlc@trinnylondon.com
    web: https://trinnylondon.com/uk/
    twitter: https://twitter.com/trinnylondon?lang=en
    description: "Trinny Woodall is a beauty entrepreneur and English TV celebrity. Founder of Trinny London, fashion and makeover expert."
  john:
    name: Victoria
    display_name: Victoria  
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: inthefrow@gmail.com
    web: https://www.inthefrow.com/
    twitter: https://twitter.com/inthefrow
    description: "With a PHD in fashion, a best-selling fashion book, “The New Fashion Rules,” Victoria is the lady behind the multi award-winning fashion, travel and beauty blog, Inthefrow."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
