# Site
name: "AL Study Team"
description: "알고리즘 발표자료를 업로드하는 블로그."

baseurl:
include: ["_pages"]
permalink: /:title/  

logo: 'assets/images/logo.png'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
