# Site
name: "MapleSage"
title: "MapleSage"
description: "Discover a smarter approach to business growth"
meta_description: "Inbound Marketing Agency"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /maplesage.co/
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Parvind
    display_name: Parvind
    gravatar: e9c1d461b32263d2a14627a894fea88b
    email: parvind@maplesage.com
    web: https://maplesage.com
    twitter: https://twitter.com/Maple_Sage
    description: "MapleSage is a full-service, integrated software solution, services, inbound marketing and communications agency based out of Gurgaon, Haryana - India. We specialize in providing platform services, consulting services, marketing & advertising services, to SME's. A new kind of agency – one that combines enterprise-level technology implementation, and value-added marketing and analytics services."
  john:
    name: parvind
    display_name: Parvind
    gravatar: e9c1d461b32263d2a14627a894fea88b
    email: parvind@maplesage.com
    web: https://maplesage.co
    twitter: https://twitter.com/Maple_Sage
    description: "MapleSage is a full-service, integrated software solution, services, inbound marketing and communications agency based out of Gurgaon, Haryana - India. We specialize in providing platform services, consulting services, marketing & advertising services, to SME's. A new kind of agency – one that combines enterprise-level technology implementation, and value-added marketing and analytics services."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
