# Site
name: "DePaul Bioinformatics"
title: "DePaul Bioinformatics"
description: "A repository for DePaul University bioinformatics contributions."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: https://depaulbioinformatics.github.io
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Collections
collections:
  teams:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  members:
    output: true
    permalink: /:collection/:path/
  software:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

all_sections: ["Projects", "Publications", "Software", "Teams", "Members", Status", "Funding Agency"]
member_types: ["Principal Investigators", "Co-Principal Investigators", "PHD Students", "Master's Students", "Undergraduate Students", "Alumni", "Members" ]

# Defaults
defaults:
  # _teams
  - scope:
      path: ""
      type: teams
    values:
      post_toc: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      post_toc: true
  # _members
  - scope:
      path: ""
      type: members
    values:
      post_toc: true
  # _software
  - scope:
      path: ""
      type: software
    values:
      post_toc: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      post_toc: true


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
